// __mocks__/@prisma/client.ts
// Manual Jest mock for `@prisma/client`. Jest automatically substitutes
// this file for the real package in every test (it lives in a __mocks__
// directory adjacent to node_modules — no explicit jest.mock() call
// needed anywhere application code imports `@prisma/client`).
//
// Every `new PrismaClient()` call anywhere in the codebase (auth.routes,
// auth.middleware, user.routes, rbac.middleware, token.service) returns
// this SAME `prismaMock` object, so a test can configure a return value
// once and have every module observe it consistently — including calls
// made inside `prisma.$transaction(async (tx) => { ... })`.
//
// Test files import `prismaMock` directly from this file (relative path)
// rather than from "@prisma/client", so `tsc` — which has no notion of
// Jest's module-mocking indirection — can resolve the export normally.

export interface PrismaMockClient {
  user: {
    findUnique: jest.Mock;
    create: jest.Mock;
    delete: jest.Mock;
  };
  role: {
    upsert: jest.Mock;
  };
  refreshToken: {
    create: jest.Mock;
    findUnique: jest.Mock;
    update: jest.Mock;
    updateMany: jest.Mock;
  };
  workoutSession: {
    findFirst: jest.Mock;
    findMany: jest.Mock;
    updateMany: jest.Mock;
  };
  coachClient: {
    findUnique: jest.Mock;
  };
  $transaction: jest.Mock;
}

export const prismaMock: PrismaMockClient = {
  user: {
    findUnique: jest.fn(),
    create: jest.fn(),
    delete: jest.fn(),
  },
  role: {
    upsert: jest.fn(),
  },
  refreshToken: {
    create: jest.fn(),
    findUnique: jest.fn(),
    update: jest.fn(),
    updateMany: jest.fn(),
  },
  workoutSession: {
    findFirst: jest.fn(),
    findMany: jest.fn(),
    updateMany: jest.fn(),
  },
  coachClient: {
    findUnique: jest.fn(),
  },
  $transaction: jest.fn(),
};

// Defined after `prismaMock` is fully constructed (rather than inline in
// the object literal above) so the implementation can reference
// `prismaMock` without a circular self-reference during initialization.
prismaMock.$transaction.mockImplementation(async (arg: unknown) => {
  if (typeof arg === "function") {
    return (arg as (tx: PrismaMockClient) => unknown)(prismaMock);
  }
  return Promise.all(arg as Promise<unknown>[]);
});

export const PrismaClient: any = jest.fn().mockImplementation(() => prismaMock);

// Mirrors the `RoleCode` enum generated by Prisma from prisma/schema.prisma.
export const RoleCode = {
  ADMIN: "ADMIN",
  COACH: "COACH",
  SUBSCRIBER: "SUBSCRIBER",
  USER: "USER",
  GYM_PARTNER: "GYM_PARTNER",
  SUPPORT_OPS: "SUPPORT_OPS",
} as const;
